In [26]:
import pandas as pd
from sqlalchemy import create_engine

In [27]:


engine = create_engine('mysql+pymysql://root:@127.0.0.1:3306/inventory_db')

In [3]:
tables = pd.read_sql("SHOW TABLES", engine)
print(tables)

  Tables_in_inventory_db
0        begin_inventory
1          end_inventory
2        purchase_prices
3              purchases
4                  sales
5         vendor_invoice

In [4]:
pd.read_sql("Select count(*) from purchases",engine)

   count(*)
0   2372474

In [5]:
for table in tables.iloc[:, 0]:
    print('-'*50, table, '-'*50)
    
    count = pd.read_sql(f"SELECT COUNT(*) as count FROM {table}", engine)
    print('Count of records :', count.iloc[0, 0])
    display(pd.read_sql(f"SELECT * FROM {table} LIMIT 5", engine))

-------------------------------------------------- begin_inventory --------------------------------------------------
Count of records : 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory --------------------------------------------------
Count of records : 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices --------------------------------------------------
Count of records : 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases --------------------------------------------------
Count of records : 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales --------------------------------------------------
Count of records : 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice --------------------------------------------------
Count of records : 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [6]:
purchase_prices = pd.read_sql(
    "SELECT * FROM purchase_prices WHERE VendorNumber = 4466",
    engine
)

purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
purchases = pd.read_sql(
    "SELECT * FROM purchases WHERE VendorNumber = 4466",
    engine
)

purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [8]:
sales = pd.read_sql(
    "SELECT * FROM sales WHERE VendorNo = 4466",
    engine
)

sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [9]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [10]:
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [11]:
vendor_invoice = pd.read_sql(
    "SELECT * FROM vendor_invoice WHERE VendorNumber = 4466",
    engine
)

vendor_invoice.head()

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None

In [12]:
sales.groupby('Brand')[['SalesDollars','SalesPrice','SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

In [13]:
freight_summary = pd.read_sql("""
SELECT 
    VendorNumber, 
    SUM(Freight) AS FreightCost
FROM vendor_invoice
GROUP BY VendorNumber
""", engine)

freight_summary.head()

   VendorNumber  FreightCost
0             2        27.08
1            54         0.48
2            60       367.52
3           105        62.39
4           200         6.19

In [16]:
purchase_summary = pd.read_sql("""
SELECT 
    VendorNumber,
    VendorName,
    Brand,
    PurchasePrice,
    SUM(Quantity) AS TotalPurchaseQuantity,
    SUM(Dollars) AS TotalPurchaseDollars
FROM purchases
GROUP BY VendorNumber, VendorName, Brand, PurchasePrice
""", engine)

In [17]:
price_df = pd.read_sql("""
SELECT Brand, Volume, Price AS ActualPrice
FROM purchase_prices
""", engine)

df = purchase_summary.merge(price_df, on='Brand', how='left')

df.head()

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750,36.99
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750,134.49
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750,14.99
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750,14.99

In [18]:
df

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750,36.99
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750,134.49
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750,14.99
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750,14.99
...,...,...,...,...,...,...,...,...
10688,173357,TAMWORTH DISTILLING,2804,32.14,210.0,6749.40,750,44.99
10689,173357,TAMWORTH DISTILLING,3666,18.79,520.0,9770.80,375,24.99
10690,173357,TAMWORTH DISTILLING,3848,23.30,28.0,652.40,750,30.99
10691,173357,TAMWORTH DISTILLING,3909,19.37,1232.0,23863.84,750,24.99
10692,201359,FLAVOR ESSENCE INC,90609,17.00,1.0,17.00,162.5,24.99

In [21]:
df = df[df['PurchasePrice'] >= 0]

In [22]:
df

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750,36.99
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750,134.49
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750,14.99
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750,14.99
...,...,...,...,...,...,...,...,...
10688,173357,TAMWORTH DISTILLING,2804,32.14,210.0,6749.40,750,44.99
10689,173357,TAMWORTH DISTILLING,3666,18.79,520.0,9770.80,375,24.99
10690,173357,TAMWORTH DISTILLING,3848,23.30,28.0,652.40,750,30.99
10691,173357,TAMWORTH DISTILLING,3909,19.37,1232.0,23863.84,750,24.99
10692,201359,FLAVOR ESSENCE INC,90609,17.00,1.0,17.00,162.5,24.99

In [24]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [28]:
sales_summary = pd.read_sql_query("""
SELECT
    VendorNo,
    Brand,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars DESC
""", engine)

sales_summary.head()

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,1128,1233,5.101920e+06,672819.31,142049.0,260999.20
1,4425,3405,4.819073e+06,561512.37,160247.0,294438.66
2,17035,8068,4.538121e+06,461140.15,187140.0,343854.07
3,3960,4261,4.475973e+06,420050.01,200412.0,368242.80
4,3960,3545,4.223108e+06,545778.28,135838.0,249587.83

In [29]:
df = purchase_summary.merge(
    price_df,
    on='Brand',
    how='left'
)

df = df.merge(
    sales_summary,
    left_on=['VendorNumber', 'Brand'],
    right_on=['VendorNo', 'Brand'],
    how='left'
)

df = df.merge(
    freight_summary,
    on='VendorNumber',
    how='left'
)
df = df[df['PurchasePrice'] >= 0]

In [30]:
df

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750,36.99,2.0,665.82,295.92,18.0,2.00,27.08
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750,134.49,NaN,NaN,NaN,NaN,NaN,0.48
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750,14.99,60.0,704.53,494.67,47.0,37.01,367.52
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750,14.99,NaN,NaN,NaN,NaN,NaN,367.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10688,173357,TAMWORTH DISTILLING,2804,32.14,210.0,6749.40,750,44.99,173357.0,6298.60,3194.29,140.0,110.33,202.50
10689,173357,TAMWORTH DISTILLING,3666,18.79,520.0,9770.80,375,24.99,173357.0,8996.40,4873.05,360.0,141.19,202.50
10690,173357,TAMWORTH DISTILLING,3848,23.30,28.0,652.40,750,30.99,173357.0,185.94,92.97,6.0,4.71,202.50
10691,173357,TAMWORTH DISTILLING,3909,19.37,1232.0,23863.84,750,24.99,173357.0,24540.18,14469.21,982.0,773.87,202.50
10692,201359,FLAVOR ESSENCE INC,90609,17.00,1.0,17.00,162.5,24.99,201359.0,1474.41,1324.47,59.0,1.24,0.09

In [31]:
df.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
PurchasePrice            float64
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
Volume                       str
ActualPrice              float64
VendorNo                 float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalSalesQuantity       float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [32]:
df.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
PurchasePrice              0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
Volume                     0
ActualPrice                0
VendorNo                 178
TotalSalesDollars        178
TotalSalesPrice          178
TotalSalesQuantity       178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [36]:
df['VendorName'].unique()

<ArrowStringArray>
['IRA GOLDMAN AND WILLIAMS, LLP',   'AAPER ALCOHOL & CHEMICAL CO',
       'ADAMBA IMPORTS INTL INC',            'ALTAMAR BRANDS LLC',
     'AMERICAN SPIRITS EXCHANGE',          'APPOLO VINEYARDS LLC',
    'ATLANTIC IMPORTING COMPANY',               'BACARDI USA INC',
           'BANFI PRODUCTS CORP',          'STATE WINE & SPIRITS',
 ...
               'INCREDIBREW INC',           'SWEET BABY VINEYARD',
       'WALPOLE MTN VIEW WINERY',             'ZORVINO VINEYARDS',
          'BLACK COVE BEVERAGES',             'Serralles Usa LLC',
         'STARK BREWING COMPANY',               'SWEETWATER FARM',
           'TAMWORTH DISTILLING',            'FLAVOR ESSENCE INC']
Length: 128, dtype: str

In [35]:
# Convert Volume column datatype
df['Volume'] = df['Volume'].astype('float64')

# Fill missing values
df.fillna(0, inplace=True)

# Remove extra spaces from VendorName
df['VendorName'] = df['VendorName'].str.strip()

# Preview
df.head()

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750.0,36.99,2.0,665.82,295.92,18.0,2.00,27.08
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750.0,134.49,0.0,0.00,0.00,0.0,0.00,0.48
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750.0,14.99,60.0,704.53,494.67,47.0,37.01,367.52
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750.0,14.99,0.0,0.00,0.00,0.0,0.00,367.52

In [37]:
# Gross Profit
df['GrossProfit'] = (
    df['TotalSalesDollars'] - df['TotalPurchaseDollars']
)

# Profit Margin
df['ProfitMargin'] = (
    df['GrossProfit'] / df['TotalSalesDollars']
) * 100

# Stock Turnover
df['StockTurnover'] = (
    df['TotalSalesQuantity'] / df['TotalPurchaseQuantity']
)

# Sales to Purchase Ratio
df['SalesToPurchaseRatio'] = (
    df['TotalSalesDollars'] / df['TotalPurchaseDollars']
)

# Preview
df.head()

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750.0,36.99,2.0,665.82,295.92,18.0,2.00,27.08,474.94,71.331591,2.250000,3.488160
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08,-4840.24,-807.029478,0.075000,0.110250
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750.0,134.49,0.0,0.00,0.00,0.0,0.00,0.48,-105.07,-inf,0.000000,0.000000
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750.0,14.99,60.0,704.53,494.67,47.0,37.01,367.52,258.37,36.672675,1.205128,1.579097
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750.0,14.99,0.0,0.00,0.00,0.0,0.00,367.52,-66.60,-inf,0.000000,0.000000

In [41]:
from sqlalchemy import text

# Drop table if already exists
with engine.connect() as conn:
    conn.execute(text("DROP TABLE IF EXISTS vendor_sales_summary"))
    conn.commit()

# Create table
create_table_query = """
CREATE TABLE vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand VARCHAR(50),
    Description VARCHAR(255),
    PurchasePrice FLOAT,
    ActualPrice FLOAT,
    Volume FLOAT,
    TotalPurchaseQuantity FLOAT,
    TotalPurchaseDollars FLOAT,
    TotalSalesQuantity FLOAT,
    TotalSalesDollars FLOAT,
    TotalSalesPrice FLOAT,
    TotalExciseTax FLOAT,
    FreightCost FLOAT,
    GrossProfit FLOAT,
    ProfitMargin FLOAT,
    StockTurnover FLOAT,
    SalesToPurchaseRatio FLOAT
)
"""

with engine.connect() as conn:
    conn.execute(text(create_table_query))
    conn.commit()

In [42]:
df

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750.0,36.99,2.0,665.82,295.92,18.0,2.00,27.08,474.94,71.331591,2.250000,3.488160
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08,-4840.24,-807.029478,0.075000,0.110250
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750.0,134.49,0.0,0.00,0.00,0.0,0.00,0.48,-105.07,-inf,0.000000,0.000000
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750.0,14.99,60.0,704.53,494.67,47.0,37.01,367.52,258.37,36.672675,1.205128,1.579097
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750.0,14.99,0.0,0.00,0.00,0.0,0.00,367.52,-66.60,-inf,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10688,173357,TAMWORTH DISTILLING,2804,32.14,210.0,6749.40,750.0,44.99,173357.0,6298.60,3194.29,140.0,110.33,202.50,-450.80,-7.157146,0.666667,0.933209
10689,173357,TAMWORTH DISTILLING,3666,18.79,520.0,9770.80,375.0,24.99,173357.0,8996.40,4873.05,360.0,141.19,202.50,-774.40,-8.607888,0.692308,0.920743
10690,173357,TAMWORTH DISTILLING,3848,23.30,28.0,652.40,750.0,30.99,173357.0,185.94,92.97,6.0,4.71,202.50,-466.46,-250.865871,0.214286,0.285009
10691,173357,TAMWORTH DISTILLING,3909,19.37,1232.0,23863.84,750.0,24.99,173357.0,24540.18,14469.21,982.0,773.87,202.50,676.34,2.756052,0.797078,1.028342
10692,201359,FLAVOR ESSENCE INC,90609,17.00,1.0,17.00,162.5,24.99,201359.0,1474.41,1324.47,59.0,1.24,0.09,1457.41,98.846996,59.000000,86.730000

In [44]:
import numpy as np

# Replace inf and -inf with 0
df.replace([np.inf, -np.inf], 0, inplace=True)

# Replace NaN with 0
df.fillna(0, inplace=True)

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750.0,36.99,2.0,665.82,295.92,18.0,2.00,27.08,474.94,71.331591,2.250000,3.488160
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08,-4840.24,-807.029478,0.075000,0.110250
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750.0,134.49,0.0,0.00,0.00,0.0,0.00,0.48,-105.07,0.000000,0.000000,0.000000
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750.0,14.99,60.0,704.53,494.67,47.0,37.01,367.52,258.37,36.672675,1.205128,1.579097
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750.0,14.99,0.0,0.00,0.00,0.0,0.00,367.52,-66.60,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10688,173357,TAMWORTH DISTILLING,2804,32.14,210.0,6749.40,750.0,44.99,173357.0,6298.60,3194.29,140.0,110.33,202.50,-450.80,-7.157146,0.666667,0.933209
10689,173357,TAMWORTH DISTILLING,3666,18.79,520.0,9770.80,375.0,24.99,173357.0,8996.40,4873.05,360.0,141.19,202.50,-774.40,-8.607888,0.692308,0.920743
10690,173357,TAMWORTH DISTILLING,3848,23.30,28.0,652.40,750.0,30.99,173357.0,185.94,92.97,6.0,4.71,202.50,-466.46,-250.865871,0.214286,0.285009
10691,173357,TAMWORTH DISTILLING,3909,19.37,1232.0,23863.84,750.0,24.99,173357.0,24540.18,14469.21,982.0,773.87,202.50,676.34,2.756052,0.797078,1.028342
10692,201359,FLAVOR ESSENCE INC,90609,17.00,1.0,17.00,162.5,24.99,201359.0,1474.41,1324.47,59.0,1.24,0.09,1457.41,98.846996,59.000000,86.730000

In [45]:
df.to_sql(
    name='vendor_sales_summary',
    con=engine,
    if_exists='replace',
    index=False,
    method='multi',
    chunksize=1000
)

10693

In [46]:
pd.read_sql(
    "SELECT * FROM vendor_sales_summary LIMIT 5",
    engine
)

,VendorNumber,VendorName,Brand,PurchasePrice,TotalPurchaseQuantity,TotalPurchaseDollars,Volume,ActualPrice,VendorNo,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax,FreightCost,GrossProfit,ProfitMargin,StockTurnover,SalesToPurchaseRatio
0,2,"IRA GOLDMAN AND WILLIAMS, LLP",90085,23.86,8.0,190.88,750.0,36.99,2.0,665.82,295.92,18.0,2.00,27.08,474.94,71.331591,2.250000,3.488160
1,2,"IRA GOLDMAN AND WILLIAMS, LLP",90609,17.00,320.0,5440.00,162.5,24.99,2.0,599.76,449.82,24.0,0.52,27.08,-4840.24,-807.029478,0.075000,0.110250
2,54,AAPER ALCOHOL & CHEMICAL CO,990,105.07,1.0,105.07,3750.0,134.49,0.0,0.00,0.00,0.0,0.00,0.48,-105.07,0.000000,0.000000,0.000000
3,60,ADAMBA IMPORTS INTL INC,771,11.44,39.0,446.16,750.0,14.99,60.0,704.53,494.67,47.0,37.01,367.52,258.37,36.672675,1.205128,1.579097
4,60,ADAMBA IMPORTS INTL INC,3401,11.10,6.0,66.60,1750.0,14.99,0.0,0.00,0.00,0.0,0.00,367.52,-66.60,0.000000,0.000000,0.000000

In [49]:
import os
import logging
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

# ================= CREATE LOGS FOLDER ================= #

os.makedirs("logs", exist_ok=True)

# ================= LOGGING CONFIGURATION ================= #

logging.basicConfig(
    filename='logs/get_vendor_summary.log',
    level=logging.DEBUG,
    format='%(asctime)s - %(levelname)s - %(message)s',
    filemode='a'
)

# ================= MYSQL CONNECTION ================= #

engine = create_engine(
    "mysql+pymysql://root:@localhost/inventory_db",
    pool_pre_ping=True,
    pool_recycle=3600
)

# ================= CLEANING FUNCTION ================= #

def clean_data(df):

    logging.info("Data cleaning started")

    # Convert datatype
    df['Volume'] = pd.to_numeric(
        df['Volume'],
        errors='coerce'
    )

    # Fill missing values
    df.fillna(0, inplace=True)

    # Remove spaces
    df['VendorName'] = (
        df['VendorName']
        .astype(str)
        .str.strip()
    )

    df['Description'] = (
        df['Description']
        .astype(str)
        .str.strip()
    )

    # ================= KPI CREATION ================= #

    # Gross Profit
    df['GrossProfit'] = (
        df['TotalSalesDollars']
        - df['TotalPurchaseDollars']
    )

    # Profit Margin
    df['ProfitMargin'] = np.where(
        df['TotalSalesDollars'] != 0,

        (
            df['GrossProfit']
            / df['TotalSalesDollars']
        ) * 100,

        0
    )

    # Stock Turnover
    df['StockTurnover'] = np.where(
        df['TotalPurchaseQuantity'] != 0,

        df['TotalSalesQuantity']
        / df['TotalPurchaseQuantity'],

        0
    )

    # Sales To Purchase Ratio
    df['SalesToPurchaseRatio'] = np.where(
        df['TotalPurchaseDollars'] != 0,

        df['TotalSalesDollars']
        / df['TotalPurchaseDollars'],

        0
    )

    # Remove inf values
    df.replace(
        [np.inf, -np.inf],
        0,
        inplace=True
    )

    df.fillna(0, inplace=True)

    logging.info("Data cleaning completed")

    return df


# ================= MAIN FUNCTION ================= #

def create_vendor_summary():

    logging.info("Vendor summary creation started")

    query = """

    WITH FreightSummary AS (

        SELECT
            VendorNumber,
            SUM(Freight) AS FreightCost

        FROM vendor_invoice

        GROUP BY VendorNumber
    ),

    PurchaseSummary AS (

        SELECT

            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.Description,
            p.PurchasePrice,

            pp.Price AS ActualPrice,
            pp.Volume,

            SUM(p.Quantity) AS TotalPurchaseQuantity,
            SUM(p.Dollars) AS TotalPurchaseDollars

        FROM purchases p

        JOIN purchase_prices pp
            ON p.Brand = pp.Brand

        WHERE p.PurchasePrice > 0

        GROUP BY

            p.VendorNumber,
            p.VendorName,
            p.Brand,
            p.Description,
            p.PurchasePrice,
            pp.Price,
            pp.Volume
    ),

    SalesSummary AS (

        SELECT

            VendorNo,
            Brand,

            SUM(SalesQuantity) AS TotalSalesQuantity,
            SUM(SalesDollars) AS TotalSalesDollars,
            SUM(SalesPrice) AS TotalSalesPrice,
            SUM(ExciseTax) AS TotalExciseTax

        FROM sales

        GROUP BY VendorNo, Brand
    )

    SELECT

        ps.VendorNumber,
        ps.VendorName,
        ps.Brand,
        ps.Description,
        ps.PurchasePrice,
        ps.ActualPrice,
        ps.Volume,

        ps.TotalPurchaseQuantity,
        ps.TotalPurchaseDollars,

        ss.TotalSalesQuantity,
        ss.TotalSalesDollars,
        ss.TotalSalesPrice,
        ss.TotalExciseTax,

        fs.FreightCost

    FROM PurchaseSummary ps

    LEFT JOIN SalesSummary ss
        ON ps.VendorNumber = ss.VendorNo
        AND ps.Brand = ss.Brand

    LEFT JOIN FreightSummary fs
        ON ps.VendorNumber = fs.VendorNumber

    ORDER BY ps.TotalPurchaseDollars DESC

    """

    # ================= FETCH DATA ================= #

    vendor_sales_summary = pd.read_sql_query(
        query,
        engine
    )

    logging.info("SQL query executed successfully")

    # ================= CLEAN DATA ================= #

    vendor_sales_summary = clean_data(
        vendor_sales_summary
    )

    # ================= STORE INTO MYSQL ================= #

    vendor_sales_summary.to_sql(
        name='vendor_sales_summary',
        con=engine,
        if_exists='replace',
        index=False,
        method='multi',
        chunksize=1000
    )

    logging.info("vendor_sales_summary table created successfully")

    return vendor_sales_summary


# ================= RUN FUNCTION ================= #

vendor_sales_summary = create_vendor_summary()

# ================= PREVIEW DATA ================= #

print(vendor_sales_summary.head())

   VendorNumber                VendorName  Brand              Description  \
0          1128         BROWN-FORMAN CORP   1233  Jack Daniels No 7 Black
1          4425     MARTIGNETTI COMPANIES   3405    Tito's Handmade Vodka
2         17035         PERNOD RICARD USA   8068         Absolut 80 Proof
3          3960  DIAGEO NORTH AMERICA INC   4261   Capt Morgan Spiced Rum
4          3960  DIAGEO NORTH AMERICA INC   3545          Ketel One Vodka

   PurchasePrice  ActualPrice  Volume  TotalPurchaseQuantity  \
0          26.27        36.99  1750.0               145080.0
1          23.19        28.99  1750.0               164038.0
2          18.24        24.99  1750.0               187407.0
3          16.17        22.99  1750.0               201682.0
4          21.89        29.99  1750.0               138109.0

   TotalPurchaseDollars  TotalSalesQuantity  TotalSalesDollars  \
0            3811251.60            142049.0       5.101920e+06
1            3804041.22            160247.0       4.819073e+06
2            3418303.68            187140.0       4.538121e+06
3            3261197.94            200412.0       4.475973e+06
4            3023206.01            135838.0       4.223108e+06

   TotalSalesPrice  TotalExciseTax  FreightCost  GrossProfit  ProfitMargin  \
0        672819.31       260999.20     68601.68   1290667.91     25.297693
1        561512.37       294438.66    144929.24   1015032.27     21.062810
2        461140.15       343854.07    123780.22   1119816.92     24.675786
3        420050.01       368242.80    257032.07   1214774.94     27.139908
4        545778.28       249587.83    257032.07   1199901.61     28.412764

   StockTurnover  SalesToPurchaseRatio
0       0.979108              1.338647
1       0.976890              1.266830
2       0.998575              1.327594
3       0.993703              1.372493
4       0.983556              1.396897